### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by porglezomp** [kevinmehall/rust-vcd#6]
Is there anything else that should be done before publishing a new version? I'm currently depending on the git head for the fixes, but I'd like to be able to follow a release instead.

**Comment by kevinmehall** [comment]
Now that you got me to revisit this library, I started adding a `ValueVector` type with inline storage such that `Command::ChangeVector` doesn't require allocating a `Vec<Value>` in the common case. If I don't finish that in the next few days, I'll just publish 0.4, since there's not much harm in doing an 0.5 later for another breaking change.

**Comment by kevinmehall** [comment]
Published [0.4.0](https://github.com/kevinmehall/rust-vcd/releases/tag/0.4.0). Thanks again for your fixes!
